public with sharing class MyCalculator {
    public static Integer add(Integer a, Integer b) {
        return a + b;
    }
    public static Integer subtract(Integer a, Integer b) {
        return a - b;
    }
    public static Integer multiply(Integer a, Integer b) {
        return a * b;
    }
    public static Integer divide(Integer a, Integer b) {
        return a / b;
    }
    public static Double circlearea(Double a) {
        return Math.pi * a * a;
    }
    public Integer adding(Integer a, Integer b) {
        return a + b;
    }
    public Integer subtracting(Integer a, Integer b) {
        return a - b;
    }
    public Decimal multiplying(Decimal a, Decimal b) {
        return a * b;
    }
    public Decimal dividing(Decimal a, Decimal b) {
        return a / b;
    }
    public static Decimal circlecircumference(Decimal a) {
        return 2 * Math.pi * a;
    }
}